version: '3'
services:
  jupyter-server:
    build: ./jupyter
    image: react_jupyter-jupyter:latest
    ports:
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  fastapi:
    build: ./fastapi
    image: react_jupyter-fastapi:latest
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  jupyter-react:
    build: ./jupyter_react
    image: react_jupyter-jupyter-react:latest
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
